package com.fist.rmms_backend;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.CacheControl;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The handful of deployment settings the map pages need, served as a plain
 * script that defines {@code window.KL_CONFIG}.
 *
 * <h2>Why a generated script and not a JSON endpoint</h2>
 * The viewer builds its MapLibre map at script-evaluation time
 * ({@code const map = new maplibregl.Map(...)} in 02-map-core.js), so the glyph
 * URL and the starting view have to be present <em>before</em> that line runs.
 * A classic {@code <script src>} is synchronous and fits the ordered-script
 * architecture the viewer already uses; a {@code fetch} would mean restructuring
 * map construction around a promise for no gain.
 *
 * <h2>What belongs here</h2>
 * Only values an operator might reasonably change per deployment: the third-party
 * services the browser talks to, and where the map opens. It is served under
 * {@code /js/**}, which is public, so nothing secret may be added — these are all
 * values the browser reveals anyway by requesting them.
 *
 * <p>Sent {@code no-cache} rather than with the 30-day header the static assets
 * carry: this file has no {@code ?v=} to bump, so a settings change must reach
 * the browser on the next reload.
 */
@RestController
public class ClientConfigController {

    private final String glyphsUrl;
    private final String routingUrl;
    private final double centerLng;
    private final double centerLat;
    private final double zoom;

    private final ObjectMapper om = new ObjectMapper();

    public ClientConfigController(
            // MapLibre needs a glyph server to render any symbol label. The default
            // is MapLibre's public demo host, which carries no availability promise —
            // point this at a self-hosted glyph server for production.
            @Value("${app.map.glyphs-url:https://demotiles.maplibre.org/font/{fontstack}/{range}.pbf}") String glyphsUrl,
            // Public OSRM demo server by default: rate-limited and unsupported. Host
            // your own OSRM (or use a keyed routing API) and set this.
            @Value("${app.routing.url:https://router.project-osrm.org/route/v1/driving/}") String routingUrl,
            @Value("${app.map.center-lng:76.95}") double centerLng,
            @Value("${app.map.center-lat:8.52}") double centerLat,
            @Value("${app.map.zoom:9}") double zoom) {
        this.glyphsUrl = glyphsUrl;
        this.routingUrl = routingUrl;
        this.centerLng = centerLng;
        this.centerLat = centerLat;
        this.zoom = zoom;
    }

    @GetMapping(value = "/js/runtime-config.js", produces = "application/javascript")
    public ResponseEntity<String> config() throws Exception {
        Map<String, Object> cfg = new LinkedHashMap<>();
        cfg.put("glyphsUrl", glyphsUrl);
        cfg.put("routingUrl", routingUrl);
        // [lng, lat] — MapLibre's order, which is also what Leaflet's setView is
        // handed after a reverse in map-lite.
        cfg.put("center", List.of(centerLng, centerLat));
        cfg.put("zoom", zoom);

        String js = "/* generated by ClientConfigController — edit app.map.* / app.routing.*\n"
                  + "   in application.properties, not this output. */\n"
                  + "window.KL_CONFIG=" + om.writeValueAsString(cfg) + ";\n";

        return ResponseEntity.ok()
                .contentType(MediaType.valueOf("application/javascript;charset=UTF-8"))
                .cacheControl(CacheControl.noCache())
                .body(js);
    }
}
