package com.fist.rmms_backend;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Built-in map layers shown in Layer Management (excludes auto-generated PCI / IRI-2km
 * and administrative boundaries — those live under the Administrative Boundary section).
 */
final class LayerCatalog {

    /**
     * @param editable attribute schema may be edited later (Phase 2); Condition CSV is editable
     * @param autoGenerated hidden from Layer Management for now (PCI, IRI-2km)
     */
    record LayerDef(
            String key,
            String label,
            String group,
            String table,
            String assetType,
            String geometryColumn,
            boolean rebuildTable,
            boolean editable,
            boolean autoGenerated,
            String notes
    ) {}

    /** Pavement parameters from the condition CSV / {@code condition} table. */
    static final List<Map<String, String>> CONDITION_PARAMS = List.of(
            Map.of("key", "iri", "label", "IRI"),
            Map.of("key", "rutting", "label", "Rutting"),
            Map.of("key", "pothole", "label", "Potholes"),
            Map.of("key", "crack", "label", "Crack"),
            Map.of("key", "texture", "label", "Texture"),
            Map.of("key", "patch_work", "label", "Patch work"),
            Map.of("key", "ravelling", "label", "Ravelling")
    );

    private static final List<LayerDef> LAYERS = List.of(
            new LayerDef("roadnet", "Road network", "network",
                    "roads", null, "geom", false, true, false,
                    "Shapefile-backed centreline; mixed-case attribute columns."),
            new LayerDef("roadnet2", "Full / merged road network", "network",
                    "full_road_network", null, "geom", false, true, false,
                    "Imported network by road name; free-form props in jsonb."),
            // Condition Data lives under Folders (kind=condition), one column per layer —
            // kept in BY_KEY only for schema resolve, not the flat Current Layers list.
            asset("bridge", "Bridge", "bridge"),
            asset("culvert", "Culvert", "culvert"),
            asset("furn-line", "Furniture (line)", "furniture_line"),
            asset("furn-pt", "Furniture (point)", "furniture_point"),
            asset("soil", "Sub-Grade Soil", "subgrade"),
            asset("core", "Bituminous Core", "bituminous_core"),
            asset("crust", "Pavement Crust", "pavement_crust"),
            asset("fwd", "FWD", "fwd"),
            new LayerDef("traffic", "Traffic stations", "traffic",
                    "traffic_stations", null, null, false, true, false,
                    "Linear-referenced stations; lat/lng columns, no PostGIS geom."),
            new LayerDef("video-catalog", "Video Catalogue", "video",
                    "road_video", null, null, false, true, false,
                    "NSV survey video catalogue — section_label links each row to a video file served from /videos/**; no PostGIS geometry, placement is by joining the road network on Section_Label.")
    );

    /** Condition CSV source table — resolved for folder layers with a value_column. */
    static final LayerDef CONDITION_SOURCE = new LayerDef(
            "condition", "Condition Data", "pavement",
            "condition", null, "geom", false, true, false,
            "Raw condition survey CSV; parameter layers under the Condition Data folder each pick one column.");

    /** Kept for reference / later re-enable — not listed in Layer Management now. */
    private static final List<LayerDef> AUTO_GENERATED = List.of(
            new LayerDef("pci-avg", "PCI (Composite)", "pavement",
                    "condition_segments", null, "geom", true, false, true,
                    "Auto-generated from condition segments."),
            new LayerDef("pci-worst", "PCI (Worst-Lane)", "pavement",
                    "condition_segments", null, "geom", true, false, true,
                    "Auto-generated from condition segments."),
            new LayerDef("iri2km", "Avg IRI (2 km)", "pavement",
                    "iri_2km_segments", null, "geom", true, false, true,
                    "Auto-generated roll-up — will be added to Layer Management later.")
    );

    private static final Map<String, LayerDef> BY_KEY;

    static {
        Map<String, LayerDef> m = new LinkedHashMap<>();
        for (LayerDef d : LAYERS) m.put(d.key(), d);
        m.put(CONDITION_SOURCE.key(), CONDITION_SOURCE);
        for (LayerDef d : AUTO_GENERATED) m.put(d.key(), d);
        BY_KEY = Map.copyOf(m);
    }

    private static LayerDef asset(String key, String label, String assetType) {
        return new LayerDef(key, label, "assets",
                "road_assets", assetType, "geom", false, true, false,
                "Shared road_assets table filtered by asset_type='" + assetType + "'.");
    }

    private LayerCatalog() {}

    /** Layers shown in the Current Layers list (excludes auto-generated). */
    static List<LayerDef> managed() {
        List<LayerDef> out = new ArrayList<>();
        for (LayerDef d : LAYERS) {
            if (!d.autoGenerated()) out.add(d);
        }
        return out;
    }

    static List<LayerDef> all() {
        return managed();
    }

    static Optional<LayerDef> get(String key) {
        return Optional.ofNullable(BY_KEY.get(key));
    }

    static boolean isKnownTable(String table) {
        for (LayerDef d : BY_KEY.values()) {
            if (d.table().equals(table)) return true;
        }
        if ("boundary".equals(table)) return true;
        return false;
    }
}
